
[project]
name = "doodler-generator"
version = "0.1"
requires-python = ">=3.10"
dependencies = [
    "Flask==3.1.0",
    "flask-cors==5.0.1",
    "accelerate==1.4.0",
    "torch==2.6.0",
    "transformers==4.49.0",
]

[project.optional-dependencies]
dev = [
    "pytest==8.3.4"
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}
